#include "main.h"

#include <stdio.h>
#include <stdlib.h>

#include "gba.h"
/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
#include "images/startimg.h"
#include "images/winimg.h"
#include "images/loseimg.h"
#include "images/peng.h"
#include "images/cat.h"
#include "images/frog.h"
#include "images/playimg.h"

/* TODO: */
// Add any additional states you need for your app. You are not requried to use
// these specific provided states.
enum gba_state {
  START,
  PLAY,
  WIN,
  LOSE,
};

int main(void) {
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCNT = MODE3 | BG2_ENABLE;
  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;

  Pengu pengu;
  //Pengu sPeng;
  Frend catu;
  Frend frogu;
  // Load initial application state
  enum gba_state state = START;

  while (1) {
    currentButtons = BUTTONS; // Load the current state of the buttons

    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw
    waitForVBlank();
    switch (state) {
      case START:
        //drawImageDMA(HEIGHT / 2, WIDTH / 2, PENG_WIDTH, PENG_HEIGHT, peng); // to make peng appear on the screen
        pengu.width = PENG_WIDTH;
        pengu.height = PENG_HEIGHT;
        pengu.row = 16;
        pengu.oldRow = pengu.row;
        pengu.col = 16;
        pengu.oldCol = pengu.col;
        pengu.score = 0;
        /*
        sPeng.width = PENG_WIDTH;
        sPeng.height = PENG_HEIGHT;
        sPeng.row = 2;
        sPeng.oldRow = sPeng.row;
        sPeng.col = 2;
        sPeng.oldCol = sPeng.col;
        sPeng.score = 0;
        */
        catu.width = CAT_WIDTH;
        catu.height = CAT_HEIGHT;
        catu.row = 60;
        catu.col = 70;
        catu.points = 1;
        catu.collected = 0;
        frogu.width = FROG_WIDTH;
        frogu.height = FROG_HEIGHT;
        frogu.row = 140;
        frogu.col = 180;
        frogu.points = 1;
        frogu.collected = 0;
        drawFullScreenImageDMA(startimg);               // put up the start img
        char buffer[51];
        sprintf(buffer, "Press START");                 // display string
        drawString(150, WIDTH / 2 - 30, buffer, BLUE);
        /*
        int time = vBlankCounter / 60;
        waitForVBlank();
        int direction = 3;
        
        sPeng.oldRow = sPeng.row;
        sPeng.oldCol = sPeng.col;
        if (sPeng.row + 1 >= HEIGHT - 2) {
            direction = 0;
        }
        if (sPeng.row - 1 <= 2) {
            direction = 1;
        }
        if (sPeng.col + 1 >= WIDTH - 2) {
            direction = 2;
        }
        if (sPeng.col - 1 <= 2) {
            direction = 3;
        }
        
        undrawImageDMA(sPeng.oldRow, sPeng.oldCol, sPeng.width, sPeng.height, peng);
        //time % 5 >= 0 && time % 5 <= 3 ? drawImageDMA(sPeng.row, sPeng.col, sPeng.width, sPeng.height, peng) : drawImageDMA(sPeng.row, sPeng.col, sPeng.width, sPeng.height, peng);
        drawImageDMA(sPeng.row, sPeng.col, sPeng.width, sPeng.height, peng);
        
        if (direction == 0) {
            sPeng.col++;
        }
        switch (direction) {
            case 0:
                sPeng.col++;
                break;
            case 1:
                sPeng.col--;
                break;
            case 2:
                sPeng.row--;
                break;
            case 3:
                sPeng.row++;
                break;
        }
        */

        if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) { // pressed ENTER to begin playing
            state = PLAY;
            drawFullScreenImageDMA(playimg);
        }
        // state = ?
        break;
      case PLAY:
        if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) { // pressed DELETE to reset game & go to START
            state = START;
        }
        waitForVBlank(); 
        //fillScreenDMA(LGREEN);
        drawRectDMA(40, 180, pengu.width * 2, pengu.height, BLACK);
        undrawImageDMA(pengu.oldRow, pengu.oldCol, PENG_WIDTH, PENG_HEIGHT, playimg); // to make peng disappear on the screen
        drawImageDMA(pengu.row, pengu.col, PENG_WIDTH, PENG_HEIGHT, peng); // to make peng appear on the screen
         // if cat is not collected then show, otherwise do not show
        catu.collected == 0 ? drawImageDMA(catu.row, catu.col, CAT_WIDTH, CAT_HEIGHT, cat) : drawRectDMA(catu.row, catu.col, catu.width, catu.height, BLUE);//undrawImageDMA(catu.row, catu.col, catu.height, catu.width, playimg);
        // to make frog appear on the screen 
        frogu.collected == 0 ? drawImageDMA(frogu.row, frogu.col, FROG_WIDTH, FROG_HEIGHT, frog) : drawRectDMA(frogu.row, frogu.col, frogu.width, frogu.height, BLUE); //undrawImageDMA(frogu.row, frogu.col, frogu.height, frogu.width, playimg);         
        char buffer2[20];
        sprintf(buffer2, "Friends: %d", pengu.score);                 // display string
        drawString(150, 10, buffer2, BLACK); 
        
        // collision logic for going into the cage (goal)
        if (pengu.row < 40 + pengu.height && pengu.row + pengu.height > 40 && pengu.col + pengu.width > 180 && pengu.col < 180 + pengu.width * 2) {
            if (pengu.score == 2) {
                state = WIN;
            } else {
                state = LOSE;
            }
            break;
        }
        
        if (KEY_DOWN(BUTTON_DOWN, currentButtons) && pengu.row < catu.row + catu.height && pengu.row + 1 + pengu.height > catu.row && pengu.col + pengu.width > catu.col && pengu.col < catu.col + catu.width) {
            pengu.row--;
        }
        if (KEY_DOWN(BUTTON_UP, currentButtons) && pengu.row - 1 < catu.row + catu.height && pengu.row + pengu.height > catu.row && pengu.col + pengu.width > catu.col && pengu.col < catu.col + catu.width) { 
            pengu.row++;
        }
        if (KEY_DOWN(BUTTON_LEFT, currentButtons) && pengu.row < catu.row + catu.height && pengu.row + pengu.height > catu.row && pengu.col + pengu.width > catu.col && pengu.col - 1 < catu.col + catu.width) {
            pengu.col++;
        }
        if (KEY_DOWN(BUTTON_RIGHT, currentButtons) && pengu.row < catu.row + catu.height && pengu.row + pengu.height > catu.row && pengu.col + pengu.width + 1 > catu.col && pengu.col < catu.col + catu.width) {
            pengu.col--;
        }

        // frogu collision logic
        
        if (KEY_DOWN(BUTTON_DOWN, currentButtons) && pengu.row < frogu.row + frogu.height && pengu.row + 1 + pengu.height > frogu.row && pengu.col + pengu.width > frogu.col && pengu.col < frogu.col + frogu.width) {
            pengu.row--;
           if (frogu.collected == 0) { //&& pengu.row <= frogu.row + frogu.height && frogu.row + 1 + pengu.height == frogu.row && pengu.col + pengu.width >= frogu.col && pengu.col <= frogu.col + frogu.width) {
                    pengu.score += frogu.points;
                    frogu.collected = 1;
                    undrawImageDMA(140, 0, 80, 20, playimg);
           } 
        }
        if (KEY_DOWN(BUTTON_UP, currentButtons) && pengu.row - 1 < frogu.row + frogu.height && pengu.row + pengu.height > frogu.row && pengu.col + pengu.width > frogu.col && pengu.col < frogu.col + frogu.width) {
            pengu.row++;
            if (frogu.collected == 0) { //&& pengu.row <= frogu.row + frogu.height && frogu.row + 1 + pengu.height == frogu.row && pengu.col + pengu.width >= frogu.col && pengu.col <= frogu.col + frogu.width) {
                    pengu.score += frogu.points;
                    frogu.collected = 1;
                    undrawImageDMA(140, 0, 80, 20, playimg);
           } 

        }
        if (KEY_DOWN(BUTTON_LEFT, currentButtons) && pengu.row < frogu.row + frogu.height && pengu.row + pengu.height > frogu.row && pengu.col + pengu.width > frogu.col && pengu.col - 1 < frogu.col + frogu.width) {
            pengu.col++;
            if (frogu.collected == 0) { //&& pengu.row <= frogu.row + frogu.height && frogu.row + 1 + pengu.height == frogu.row && pengu.col + pengu.width >= frogu.col && pengu.col <= frogu.col + frogu.width) {
                    pengu.score += frogu.points;
                    frogu.collected = 1;
                    undrawImageDMA(140, 0, 80, 20, playimg);
           } 

        }
        if (KEY_DOWN(BUTTON_RIGHT, currentButtons) && pengu.row < frogu.row + frogu.height && pengu.row + pengu.height > frogu.row && pengu.col + pengu.width + 1 > frogu.col && pengu.col < frogu.col + frogu.width) {
            pengu.col--;
            if (frogu.collected == 0) { //&& pengu.row <= frogu.row + frogu.height && frogu.row + 1 + pengu.height == frogu.row && pengu.col + pengu.width >= frogu.col && pengu.col <= frogu.col + frogu.width) {
                    pengu.score += frogu.points;
                    frogu.collected = 1;
                    undrawImageDMA(140, 0, 80, 20, playimg);
           } 

        }

        // further collision logic for screen bounds & seeing if collected friend

        //waitForVBlank();
        if (KEY_DOWN(BUTTON_DOWN, currentButtons) && !(KEY_DOWN(BUTTON_LEFT, currentButtons) || KEY_DOWN(BUTTON_RIGHT, currentButtons))) {
            if (pengu.row >= 144) {
                pengu.row = 144;
            } else {
                if (catu.collected == 0 && pengu.row <= catu.row + catu.height && pengu.row + 1 + pengu.height == catu.row && pengu.col + pengu.width >= catu.col && pengu.col <= catu.col + catu.width) {
                    pengu.score += catu.points;
                    catu.collected = 1;
                    undrawImageDMA(140, 0, 80, 20, playimg);
                } else {
                    pengu.oldRow = pengu.row;
                    pengu.oldCol = pengu.col;
                    pengu.row += MOVEINC;
                }
            }
        }
        if (KEY_DOWN(BUTTON_UP, currentButtons) && !(KEY_DOWN(BUTTON_LEFT, currentButtons) || KEY_DOWN(BUTTON_RIGHT, currentButtons))) {
            if (pengu.row <= 0) {
                pengu.row = 0;
            } else {
                if (catu.collected == 0 && pengu.row - 1 == catu.row + catu.height && pengu.row + pengu.height >= catu.row && pengu.col + pengu.width >= catu.col && pengu.col <= catu.col + catu.width) {
                    pengu.score += catu.points;
                    catu.collected = 1;
                    undrawImageDMA(140, 0, 80, 20, playimg);
                } else {
                    pengu.oldRow = pengu.row;
                    pengu.oldCol = pengu.col;
                    pengu.row -= MOVEINC;
                }
            }
        }
        if (KEY_DOWN(BUTTON_LEFT, currentButtons) && !(KEY_DOWN(BUTTON_DOWN, currentButtons) || KEY_DOWN(BUTTON_UP, currentButtons))) {
            if (pengu.col <= 0) {
                pengu.col = 0;
            } else {
                if (catu.collected == 0 && pengu.row <= catu.row + catu.height && pengu.row + pengu.height >= catu.row && pengu.col + pengu.width >= catu.col && pengu.col - 1 == catu.col + catu.width) {
                    pengu.score += catu.points;
                    catu.collected = 1;
                    undrawImageDMA(140, 0, 80, 20, playimg);
                } else {
                    pengu.oldRow = pengu.row;
                    pengu.oldCol = pengu.col;
                    pengu.col -= MOVEINC;
                }
            }
        }
        if (KEY_DOWN(BUTTON_RIGHT, currentButtons) && !(KEY_DOWN(BUTTON_DOWN, currentButtons) || KEY_DOWN(BUTTON_UP, currentButtons))) {
            if (pengu.col >= 224) {
                pengu.col = 224;
            } else {
                if (catu.collected == 0 && pengu.row <= catu.row + catu.height && pengu.row + pengu.height >= catu.row && pengu.col + 1 + pengu.width == catu.col && pengu.col <= catu.col + catu.width) {
                    pengu.score += catu.points;
                    catu.collected = 1;
                    undrawImageDMA(140, 0, 80, 20, playimg);
                } else {
                    pengu.oldRow = pengu.row;
                    pengu.oldCol = pengu.col;
                    pengu.col += MOVEINC;
                }
            }
        } 

        //waitForVBlank();

        // state = ?
        break;
      case WIN:
        if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) { // pressed DELETE to reset game & go to STARiT
            state = START;
        }
        waitForVBlank();
        drawFullScreenImageDMA(winimg);
        char buffer3[25];
        sprintf(buffer3, "%d friends :0", pengu.score);                 // display string
        drawString(150, 70, buffer3, BLACK); 
        // state = ?
        break;
      case LOSE:
        if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) { // pressed DELETE to reset game & go to START
            state = START;
        }
        waitForVBlank();
        drawFullScreenImageDMA(loseimg);
        char buffer4[20];
        pengu.score == 1 ? sprintf(buffer4, "%d friend!", pengu.score) : sprintf(buffer4, "%d friends!", pengu.score);                 // display string
        drawString(150, 70, buffer4, WHITE);
        waitForVBlank();
        // state = ?
        break; 
    }
    waitForVBlank();

    previousButtons = currentButtons; // Store the current state of the buttons
  }

  UNUSED(previousButtons); // You can remove this once previousButtons is used

  return 0;
}
